import Head from 'next/head'
import styles from '../styles/Home.module.css'
import 'bootstrap/dist/css/bootstrap.css'

const about = () => {
	return (
		<div className="container m-3">
			{' '}
			<Head>
				<title>About</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<div className={`border-bottom p-2 ${styles.borderWidth}`}>
				<h1 className={`fs-3  ${styles.h1}`}>about page</h1>
			</div>
		</div>
	)
}

export default about
