import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import { useEffect, useState } from 'react'
import styles from '../styles/Home.module.css'
import 'bootstrap/dist/css/bootstrap.css'
import Link from 'next/link'
import { useRouter } from 'next/router'

const Home: NextPage = () => {
	const [time, setTime] = useState(0)

	const [show, setShow] = useState(false)

	const router = useRouter()

	const gotoDetail = () => {
		router.push({
			pathname: '/posts/[postsID]',
			query: {
				postsID: 123,
				ref: 'social',
			},
		})
	}

	useEffect(() => {
		if (time > 5) {
			setShow(true)
		}
	}, [time, show])

	return (
		<div className={styles.container}>
			<Head>
				<title>First NextJS App</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<main className={styles.main}>
				<h2>{time}</h2>

				<button className="btn btn-primary" onClick={() => setTime(time + 1)}>
					increase
				</button>
				{!show || (
					<Link href="/posts/create">
						<a className="m-3">
							<button className="btn btn-info">Create Page</button>
						</a>
					</Link>
				)}

				<button onClick={gotoDetail} className="m-3 btn btn-success">
					goto
				</button>
			</main>

			<footer className={styles.footer}>
				<a
					href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
					target="_blank"
					rel="noopener noreferrer"
				>
					Powered by &#10017;{' Mr.Hung '} &#10017; And
					<span className={styles.logo}>
						<Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
					</span>
				</a>
			</footer>
		</div>
	)
}

export default Home
